version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-fucking-app
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  Install:
    - location: scripts/after_setup
      timeout: 300
      runas: root	

