#!/bin/bash
cd /home/ec2-user/Authentification

# Clean npm cache
npm cache clean --force

# Install Node.js if it's not already installed
if ! command -v node &> /dev/null
then
    echo "Node.js not found. Installing..."
    # Install Node.js (version 14.x)
    curl -fsSL https://rpm.nodesource.com/setup_14.x | bash -
    yum install -y nodejs

    

else
    echo "Node.js is already installed."

    


fi

 # Remove existing node_modules if they exist
rm -rf node_modules

echo "Running npm install to install dependencies with Nodemon later ...  "

npm install




